### ISSUE TITLE
Passing access token as a parameter in every function

### ISSUE THREAD

**Issue by gouravagrwal** [Promact/slack-erp-custom-integration-mvc#102]
Access token is being passed as a parameter in every method that calls oauth server. Instead of that we can move its generation to the place from where we actually make call to oauth server (to be specific Http Client Repository).

**Comment by siddharthashw** [comment]
Start Date - 16/12/2016
End Date - 16/12/2016
Estimated Time - 1 hours

**Comment by siddharthashw** [comment]
Fixes - #102

Those who want to use this method can check updatedAccessToken branch
There, I had done a way to fixes this above issue. And added one test case with mocking of HTTP context.

Test cases - OAuthCallRepositoryTest.cs -> GetProjectDetailsTrueAsync
Method - OAuthCallRepository.cs -> GetProjectDetailsAsync and AccessTokenOfRequestedUser

Go through the GetProjectDetailsAsync of OAuthCallRepository and GetProjectDetailsTrueAsync of OAuthCallRepositoryTest for better understanding.
