### ISSUE TITLE
List all environment variables

### ISSUE THREAD

**Issue by chintans** [Promact/slack-erp-custom-integration-mvc#11]
List out all environment variables in a text file as an instruction file. for example, create SETUP.md file and write down set up instruction for the project. make sure you use dummy values and not the actual values in instructions

**Comment by siddharthashw** [comment]
I have listed all the environment variable in SETUP.md and used all dummy value and User need to store environment variable, target as User system

**Comment by siddharthashw** [comment]
I had listed out all the environment variable and store in SETUP.md file in root folder and used all dummy value for instruction

**Comment by chintans** [comment]
I had asked for a .md file like readme.md and not a text file. In addition formatting is wrong. The document is not readable. Please look at Markdown syntax for writting properly a .md file.

**Comment by siddharthashw** [comment]
Removed SETUP.md.txt and add SETUP.md and used Markdown syntax and create pull request #22 from issue-11 branch
