### ISSUE TITLE
integrated apidoc into system to document api methods

### ISSUE THREAD

**Issue by chintans** [Promact/slack-erp-custom-integration-mvc#12]
We will be using [apidoc ](http://apidocjs.com/)in application to create proper documentation.

**Comment by chintans** [comment]
has everyone updated their api docs?

**Comment by ankit213** [comment]
I had completed api docs( in consumer app functionality)

**Comment by siddharthashw** [comment]
I had completed my portion of api doc., Leave Request, home and OAuth Controllers

**Comment by gouravagrwal** [comment]
I have also completed my portion of api doc (in Leave Report functionality)
