### ISSUE TITLE
add gulp task to run client side unit test on appveyor

### ISSUE THREAD

**Issue by chintans** [Promact/slack-erp-custom-integration-mvc#13]
Create a gulp task like 'test-ci' which should execute test cases in a CI environment with tappveyor as reporter.

**Comment by chintans** [comment]
What is the status on this?

**Comment by ankit213** [comment]
I have completed this task, but small changes in this task , I have not Create gulp task because of in this project there is no setup of gulp task. Thus I directly added  script in package.json file
