### ISSUE TITLE
add client side code coverage tool

### ISSUE THREAD

**Issue by chintans** [Promact/slack-erp-custom-integration-mvc#14]
integrate client side code coverage tool like [Istanbul](https://github.com/gotwarlost/istanbul) and link that with coveralls.

**Comment by chintans** [comment]
What is the status on this?

**Comment by ankit213** [comment]
Yet not started working on this, first I will complete oauth project task.

**Comment by ankit213** [comment]
today I have spent 4 hours on this issue, yet not working proper so not completed this issue

**Comment by ankit213** [comment]
Friday worked on this but there are display some errors like below link "https://ci.appveyor.com/project/iroshni/slack-erp-custom-integration-mvc/build/1.0.381"

**Comment by ankit213** [comment]
I have not found proper documentation for client side integration with converalls, I have referred link "https://github.com/gotwarlost/istanbul" but not getting proper solution, because in this repository integrate with travis and appveyor not support Linux command so I will try to find proper document for appveyor.

**Comment by ankit213** [comment]
I used code "- type coverage/lcov.info | coveralls/bin/coveralls.js" for generate coverage in coveralls but road block is pipe command not working in window so I try to find similar command

**Comment by ankit213** [comment]
I found similar command referring link "https://github.com/nickmerwin/node-coveralls/issues/114"
command is   "- node ./node_modules/coveralls/bin/coveralls.js < ./coverage/lcov.info" but now commands is executed but throw error  "Couldn't find a repository matching this job" 
 https://ci.appveyor.com/project/iroshni/slack-erp-custom-integration-mvc/build/1.0.440
I am trying to solve this issue. Please give any sugeestion.
