### ISSUE TITLE
Scrum bot is not working

### ISSUE THREAD

**Issue by chintans** [Promact/slack-erp-custom-integration-mvc#166]
Scrum bot is not working at all. Please fix it with highest priority.

**Comment by juliepromact** [comment]
Scrum bot is working right now.

Issue is it does not allow team leaders to interact at all as team leaders were not expected to be asked questions.

**Comment by chintans** [comment]
It is not working as I have tested my self. Scrum bot has most unusual behaviour which creates lots of doubt on how stable it is. 

@ankit213 and @juliepromact  Please ensure Scrum bot is extremely stable

**Comment by juliepromact** [comment]
Start Date - 24/02/2017
Estimated Time - 10 hours
End Date - 25/02/2017
