### ISSUE TITLE
NLog structuring for better organizing logs

### ISSUE THREAD

**Issue by chintans** [Promact/slack-erp-custom-integration-mvc#179]
right now all logs are logged by logging levels. This creates confusion for people to go through logs easily. Propose a better structure of logging which makes it easier to go through logs.

**Comment by iamronakshah** [comment]
@chintans 
right now all logs information are differentiate by Nlog level.
like error logs are in error.log file , info logs in info.log file.
so this is right or not?

and for the file format are
1) time |  file name | message

2) time :
file name :
message :

if any exception occurred then error file show only error message
and trace file shows full Stack trace

so please provide me your feedback.

**Comment by chintans** [comment]
This format was already suggested by Ankit. This does not solve issue.

**Comment by iamronakshah** [comment]
so you want to modified  Stack trace? 
or you asking about the custom layout for logs?

**Comment by iamronakshah** [comment]
I have analysed issue
and I found one solution - we can distribute log module wise.
but issue is when global exception occurs, we cannot identify the name of file (or module) from where the exception has occurred so we can put that log in general log file.

so is this correct?

**Comment by chintans** [comment]
Yes, That is Ok
Please refer to following links for detailed understanding.
https://stackify.com/nlog-guide-dotnet-logging/

https://stackify.com/csharp-logging-best-practices/
