### ISSUE TITLE
Create Admin panel for managing different options

### ISSUE THREAD

**Issue by chintans** [Promact/slack-erp-custom-integration-mvc#183]
Current Slack site has no admin panel to manage settings. Please create Admin page which allows User with Role of Administrator to manage following settings:

1. Mail Settings:
- Send mail - This setting will determine if an email should be sent to required users when user has completed his task mail. If it is set to true it will send email to associated user. Promact/slack-erp-custom-integration-mvc#184 
-  To User - This are the users who will receive mail in TO. It is similar to mail field To.
- CC User - This users will receive mail in CC. It is similar to CC field.

**Comment by siddharthashw** [comment]
Is Issue- #184 is referring to this send mail ?

Will this Mail Setting section will be added to existing side bar navigation ?

**Comment by chintans** [comment]
> Issue- #184 is referring to this send mail ?

yes

> Will this Mail Setting section will be added to existing side bar navigation ?

Yes

**Comment by siddharthashw** [comment]
Start Date : 20/02/2017
Estimated time : 4 hours
End Date : 21/02/2017

**Comment by siddharthashw** [comment]
For mockup and database analysis....
it's update of above comment
