### ISSUE TITLE
Send mail

### ISSUE THREAD

**Issue by chintans** [Promact/slack-erp-custom-integration-mvc#184]
This setting will determine if an email should be sent to required users for specified module and project-wise, when user of that project has completed his task mail or scrum meeting. If it is set to true it will send email to associated user.

Workflow would be as follows:

1. Under each module there will be a mail option with label "Mail Settings". For e.g
Scrum Bot
|___Mail Settings
Task List Bot
|___Mail Settings
Leave Management
|___Mail Settings

2. User will go under the module where it wants to enable mail settings for specific project. Each Mail settings will have a common settings "Send Mail" with Checkbox.

3. If they turn on/Check Send Mail. System will send mail according to rest of the settings of that module.

**Comment by siddharthashw** [comment]
Every user will have their own mail setting and admin will have all user's mail setting ? Is that ?

**Comment by siddharthashw** [comment]
And for option of each module we must have a side navigation panel

**Comment by chintans** [comment]
> Every user will have their own mail setting and admin will have all user's mail setting ? Is that ?

Only administrator user can manage these settings and they are system wide. 

> And for option of each module we must have a side navigation panel

Yes

**Comment by siddharthashw** [comment]
It will be user-wise or mail type wise(1. Task mail, 2. Leave and 3. Scrum)

**Comment by siddharthashw** [comment]
If not user-wise then how admin will be able to do :- *This setting will determine if an email should be sent to required users when user has completed his task mail. If it is set to true it will send email to associated user*

**Comment by chintans** [comment]
> It will be user-wise or mail type wise(1. Task mail, 2. Leave and 3. Scrum)

It is mail type wise. 

> If not user-wise then how admin will be able to do :- This setting will determine if an email should be sent to required users when user has completed his task mail. If it is set to true it will send email to associated user

Mail settings will be applied in logic where developer need to check if mail settings are enabled or not. if it's enabled send mail according to the TO and CC added while creating Mail settings. So, This will be module wise. developer of Taskmail Bot will implement functionality in it's own module according to this specification.

**Comment by chintans** [comment]
Here is an example which may help you understand the overall functionality.

As of now send mail when Taskmail is completed by User is very static. It is coded and will be sent to Team Leader only. By introducing the above feature we allow admin to configure who can receive mails for a user's task mail.
For a Project A, There are 4 developers and 1 team leader. Now when all 4 members complete taskmail from bot team leader will receive mail for task. Now If management wanted to get emails too then there would be a coding change that may be required. This would be difficult to do. instead if I can configure who can receive mails from UI in admin panel. It would be easy.

**Comment by siddharthashw** [comment]
So as above example.. And the mock-up this
![mail setting page](https://cloud.githubusercontent.com/assets/16556606/23155884/86d46844-f83a-11e6-959e-06f931abdd9a.png)

Which project details will be shown on click of taskmail-mail-setting. That is my point of distinguish.

**Comment by chintans** [comment]
TO and CC will be tag boxes and what is the purpose of having a Back button here?

**Comment by siddharthashw** [comment]
Ok I have updated TO and CC to tag box and removed back.
![mail setting page](https://cloud.githubusercontent.com/assets/16556606/23156907/d67cbcb2-f83e-11e6-8317-71dd7116bd90.png)

But my point is, How you will get that on whose task mail you are adding CC and TO. And how you will be able to know that current task mail belong to which project and which user.

**Comment by chintans** [comment]
This is explained in feature #188 . I will put group names in TO and CC. For example in To I will put group name **Team Leader** and in CC, I will put **Management** and **Team Members**. So, When a user has completed his task mail It will be sent to his project's team leader. Team Leader will be determined by querying oauth server for a user's team leader and his project.

**Comment by siddharthashw** [comment]
Ok now all scenario is clear. But If multiple configuration is done. Then which will be preferable.

And till mail setting is done. No mail will be send. Is that ?

**Comment by chintans** [comment]
There will be only 1 configuration per module.

Till Admin turns on mail settings. Mails will not be sent

**Comment by siddharthashw** [comment]
Ok I got my all point clear till now. So can I start implementation

**Comment by chintans** [comment]
DB design is pending

**Comment by siddharthashw** [comment]
![image](https://cloud.githubusercontent.com/assets/16556606/23162455/1c19dcfe-f854-11e6-806f-fc01273cd55b.png)

**Comment by chintans** [comment]
Db design is not proper. naming of the table is also wrong. Please write proper Data type. key/characteristics are also not correct.

**Comment by siddharthashw** [comment]
![image](https://cloud.githubusercontent.com/assets/16556606/23163635/3441924a-f859-11e6-8141-84478f73fd7e.png)

**Comment by siddharthashw** [comment]
I have updated the db design pls review it

**Comment by chintans** [comment]
Not proper naming of tables. Column names are not proper as well. We don't use space in names. also How will you store To and CC?

**Comment by siddharthashw** [comment]
![image](https://cloud.githubusercontent.com/assets/16556606/23163782/ef2c0f18-f859-11e6-9b38-a508a83349fb.png)

**Comment by chintans** [comment]
Not proper, same comments as above

**Comment by siddharthashw** [comment]
Start Date : 22/02/2017
Estimated time : 20 hours
End Date : 24/02/2017
