### ISSUE TITLE
Integrate Admin theme

### ISSUE THREAD

**Issue by chintans** [Promact/slack-erp-custom-integration-mvc#185]
Integrate this admin template in the application

https://github.com/puikinsh/gentelella

**Comment by ankit213** [comment]
Start Date : 20-02-2017
Estimated Time : 4 Hours
End Date : 21-02-207

**Comment by ankit213** [comment]
@chintans : The current system has three links are displayed after the user successfully login like "Task mail Report", "Leave Report", "Scrume Report", But after admin panel it will display in the left navigation When any user login then displays "add to slack user" page, after "add to slack" it will redirect to Admin panel
Is It correct?

**Comment by chintans** [comment]
> @chintans : The current system has three links are displayed after the user successfully login like "Task mail Report", "Leave Report", "Scrume Report", But after admin panel it will display in the left navigation When any user login then displays "add to slack user" page, after "add to slack" it will redirect to Admin panel
Is It correct?

Yes
