### ISSUE TITLE
To User and CC User

### ISSUE THREAD

**Issue by chintans** [Promact/slack-erp-custom-integration-mvc#187]
This are the users who will receive mail in TO or CC. It is similar to mail field **TO** or **CC**. Both fields will take input in a csv format either using tag control or a drop down. Input will either be group names (#188)  or individual email IDs.

**Comment by ankit213** [comment]
@chintans 
![mail setting page](https://cloud.githubusercontent.com/assets/9895825/23161171/08971fc0-f84f-11e6-9273-8e7735ce1b53.png)



Above is wireframe for To User and CC User, If  I click on submit button it will insert the TOUser and CCUser data in table, is it proper?  or any modification is required ?

**Comment by ankit213** [comment]
@chintans : Above functionality is included in send mail #184  or it is different functionality?  because In Send mail functionality included TO user and Cc user in Mail Setting portion. I am confused about both if both are different so please explain detail.
