### ISSUE TITLE
Group names

### ISSUE THREAD

**Issue by chintans** [Promact/slack-erp-custom-integration-mvc#188]
Create a functionality for Admin to define groups. A group is a logical collection of email. System will have few predefined groups which Admin can not delete. New groups created by Admin can be deleted by Admin. There will be 2 types of groups.

**1. Dynamic Groups**
This groups will not have any email id associated with the when created.They will dynamically create list of emails. For e.g, Group - "Team Leader" is dynamic group because for every project there is different Team Leader. So, If I add Team Leader group in To for my Project. It should automatically take Team Leader of only my project. Team Leader will be one of the predefined groups. Dynamic groups are always pre-defined they can not be created by Administrator.

List of Dynamic Groups:
1. Team Leader
2. Management
3. Team Members

**2. Static Groups**
This groups will have a static list of email ids. for example I may create a group called "HuddleWrapper" and add email ids of all the members of Huddle Wrapper. So, The list will always contain these same amount of email address.

If a User is deactivated from OAuth server his id should be removed from the group.

**Comment by ankit213** [comment]
@chintans : you have mentioned project selection in Dynamic Group but in ERP we do not have any projects, so how this project will relate with Dynamic Group ?

**Comment by chintans** [comment]
> you have mentioned project selection in Dynamic Group but in ERP we do not have any projects, so how this project will relate with Dynamic Group ?

Dynamic groups are hard coded in application. They will determine Project based on user's role and their associated project.

**Comment by siddharthashw** [comment]
what the use of email here

Issue - #188 - Create a functionality for Admin to define groups. A group is a logical collection of email.
Then you commented that 
Issue - #183 - Team Leader will be determined by querying oauth server for a user's team leader and his project

**Comment by ankit213** [comment]
@chintans 
![list of group](https://cloud.githubusercontent.com/assets/9895825/23160256/ca727774-f84b-11e6-968a-d8188392fd10.png)
![edit group](https://cloud.githubusercontent.com/assets/9895825/23160843/ff4cc4fc-f84d-11e6-9e2a-3afe29da5e66.png)
![add group](https://cloud.githubusercontent.com/assets/9895825/23161096/cc2fa764-f84e-11e6-9283-ea515675d7d5.png)




Above given three wireframe is it proper or not ?

**Comment by chintans** [comment]
No, It is not proper. It is mentioned in requirement that a Static group is collection of email ids not a single email.

**Comment by ankit213** [comment]
I have updated above wireframe please check it and let me know is it proper or not?

**Comment by chintans** [comment]
Looks good, Please provide DB design

**Comment by ankit213** [comment]
Db design is provided in #184 (Table name is "**Group**")

**Comment by ankit213** [comment]
@chintans  : **Dynamic Groups :** The flow, which can I understand is When a user is login at that time fetch all team leaders, team members and management from of Oauth server and create three dynamic groups
Team Leader,Management &Team Members, then I will login second time by user at that time update existing dynamic group. Is it correct or need any change in flow ?

**Comment by ankit213** [comment]
Estimation Time For Static Groups(Add/Edit/Delete) Functionality
Start Date :  22-02-2017
Estimation Time : 20 Hours + (10 Hours For Server Side And Client Side Test Cases) = 30 Hours
End Date: 28-02-2017
