### ISSUE TITLE
Updated angular2 version to 2.4.0 to compatible with md2 latest version

### ISSUE THREAD

**Issue by siddharthashw** [Promact/slack-erp-custom-integration-mvc#203]
Update the angular2 version to 2.4.0 to compatible with md2 latest version - 0.0.15

**Comment by siddharthashw** [comment]
Start Date : 27/02/2017
Estimated time : 3 hours
End Date : 27/02/2017

**Comment by chintans** [comment]
It should be the latest version. Which I think is 2.4.8

**Comment by siddharthashw** [comment]
Its working on 2.4.0 and its compatible with md2 latest version

**Comment by chintans** [comment]
So, have you confirmed it will not work with 2.4.8? since this is a minor update to 2.4 series

**Comment by siddharthashw** [comment]
It will work on 2.4.8.

So, I will update it to 2.4.8
