### ISSUE TITLE
Add a proper build status table to distingiush client side and server side code coverage

### ISSUE THREAD

**Issue by chintans** [Promact/slack-erp-custom-integration-mvc#233]
right now on README.md page there are just 2 coverage badge. It is not easy to know which once is server side or which one is client side. Create a proper table in markdown to show which one is client side and which one is server side. You may take reference as given in the following repo

https://github.com/dotnet/cli

look at Build Status Section

**Comment by siddharthashw** [comment]
Start Date : 06/03/2017
Estimated time : 0.5 hours
End Date : 06/03/2017
