### ISSUE TITLE
Add Link, Unlink and List command to ScrumBot

### ISSUE THREAD

**Issue by chintans** [Promact/slack-erp-custom-integration-mvc#241]
Implement these new commands

Link
This command will allow a team leader to link a channel with a project. Team leader can do something like 

`link wrapper`

If project is already linked then it should show appropriate message else it should show project linked successfully.

Unlink
This command will allow a team leader to unlink a channel with a project.

`unlink wrapper`

Appropriate messages should be shown.

List
A team leader can issue list command to retrieve list of projects which are linked and which are pending.

`list links`

|  ProjectId  | Name  | Channel  |
|---|---|---|
| 1  | Wrapper  | huddle-wrapper  |
| 2  | huddle  | huddle  |

All three commands are only accessible to Team Leader role.

**Comment by juliepromact** [comment]
>Unlink
This command will allow a team leader to unlink a channel with a project.
`unlink wrapper`

As a slack channel would be linked to only one OAuth project, is it necessary to specify the project name in unlink command ? 

>List
A team leader can issue list command to retrieve list of projects which are linked and which are pending.
`list links`

Only the list of projects of which the user is team leader must be displayed or all the projects ? 

( A general rule which has been followed while developing scrum bot, i.e only active users, active projects and projects which have an active team leader would be able to perform any desired action using commands, would be followed for these three commands too.)

**Comment by juliepromact** [comment]
In case of commands `link wrapper` and `unlink wrapper`, the project name could be as short as "wrapper" or could be like "The Imitation Game-A Strife of Power". So the command would become `link The Imitation Game-A Strife of Power`. 
It is difficult to differentiate which is a command and which is a simple statement like "_link the channels @ankit213_". So if `link` or `unlink` word is encountered as first word, it will be considered as a command and process it. 
Slash command for link could be used instead.

**Comment by chintans** [comment]
> As a slack channel would be linked to only one OAuth project, is it necessary to specify the project name in unlink command ?

Yes, make it mandatory to write project name. It will be helpful in avoiding confusion.

> Only the list of projects of which the user is team leader must be displayed or all the projects ?

Only active projects associated to that team leader

> In case of commands link wrapper and unlink wrapper, the project name could be as short as "wrapper" or could be like "The Imitation Game-A Strife of Power". So the command would become link The Imitation Game-A Strife of Power.
It is difficult to differentiate which is a command and which is a simple statement like "link the channels @ankit213". So if link or unlink word is encountered as first word, it will be considered as a command and process it.

if there are spaces in the name of project then user must write name in double quote. but current structure is proper `link <projectname>`

**Comment by juliepromact** [comment]
>if there are spaces in the name of project then user must write name in double quote. but current structure is proper link <projectname>

I think it would be better to use double quote even for project names with no spaces in between, so that a uniform syntax like `link "sci"` can be maintained and it would also differentiate from a normal statement like `link it`
