### ISSUE TITLE
Scrum Report Not Working Proper

### ISSUE THREAD

**Issue by ankit213** [Promact/slack-erp-custom-integration-mvc#259]
When a user is the team leader in project1 and same user is a team member in project2, so when scrum report is generated it display only proejct1 not both projects. It should display both projects.

**Comment by siddharthashw** [comment]
Start Date : 09/03/2017
Estimated time : 4 hours
End Date : 09/03/2017

**Comment by siddharthashw** [comment]
Leave Report is also Not Working Proper. I will update it

**Comment by siddharthashw** [comment]
Start Date : 09/03/2017
Estimated time : 4 hours
End Date : 10/03/2017

**Comment by siddharthashw** [comment]
I need to change and refactor all the methods of leave-report

updated estimation 
Start Date : 09/03/2017
Estimated time : 6 hours
End Date : 10/03/2017
