### ISSUE TITLE
Slack Redmine Automation

### ISSUE THREAD

**Issue by siddharthashw** [Promact/slack-erp-custom-integration-mvc#269]
Create a slack slash command for redmine, by which slack user will be able to operate CRUD operation for redmine issues.

**Basic flow** -
When user get login from oauth-server, after that over there they need to provide there redmine API key.
Then user will be able to use redmine slash command.

**Comment by siddharthashw** [comment]
**/redmine get projectId** - Get list of 20 issue of project of own
**/redmine get projectId issueId** - Get details of particular issue of project
**/redmine create projectId Subject Description Priority Status Tracker AssignTo** - Create issue in a particular project
**/redmine update projectId Subject Description Priority Status Tracker AssignTo issueId** - Update issue in a particular project
**/redmine delete projectId issueId** - Delete a particular issue of project

@rushi216 Please review the command the provide the feedback.

**Comment by rushi216** [comment]
/redmine issues - get command help like /remind commands

**Comment by siddharthashw** [comment]
instead of /redmine issues, can we use /redmine help for help. As we have in Leave slash command

**Comment by rushi216** [comment]
My suggestions:
/redmine help - get command help like /remind command.
/redmine projects list - list all projects
/redmine issues list {projectId} - get all issues assigned to me in particular project
/redmine issues create {projectId} {Subject} {Description} {Priority} {Status} {Tracker} {AssignTo}
/redmine issues change-assignee {issueId} {AssignedTo}
/redmine issues close {issueId}
/redmine issues time-entry add {issueId} {hours} {date} {activity}

**Comment by siddharthashw** [comment]
Start Date : 14/03/2017
Estimated time : 10 hours
End Date : 15/03/2017

**Comment by siddharthashw** [comment]
/redmine issues time-entry add {issueId} {hours} {date} {activity}

For this command, my suggestion is we should use
/redmine issues time-entry {issueId} {hours} {date} {activity} instead of /redmine issues time-entry add {issueId} {hours} {date} {activity}
As we don't provide rights to user to update the time-entry
