### ISSUE TITLE
Create Wireframe for Seprate(Task Mail Bot, Scrum Bot , Leave Command and Redmine command) Functionality 

### ISSUE THREAD

**Issue by ankit213** [Promact/slack-erp-custom-integration-mvc#278]

**Comment by siddharthashw** [comment]
![add to slack](https://cloud.githubusercontent.com/assets/16556606/23984003/3499ca14-0a3d-11e7-97a9-1c7c4ae42ef0.png)
![configuration on](https://cloud.githubusercontent.com/assets/16556606/23984004/349e3d92-0a3d-11e7-8668-2ac0d8f2d732.png)
![configuration page](https://cloud.githubusercontent.com/assets/16556606/23984006/34e62d78-0a3d-11e7-8244-034615574577.png)

**Comment by siddharthashw** [comment]
![configuration page](https://cloud.githubusercontent.com/assets/16556606/23984038/5511c120-0a3d-11e7-8fa4-00083acc3896.png)
![add to slack](https://cloud.githubusercontent.com/assets/16556606/23984043/5a22e964-0a3d-11e7-9407-cd8fad3f2cd0.png)
![configuration on](https://cloud.githubusercontent.com/assets/16556606/23984048/5fa78138-0a3d-11e7-91d0-5543e679e3d7.png)

**Comment by siddharthashw** [comment]
Database Design : -
![image](https://cloud.githubusercontent.com/assets/16556606/23985486/63da4b70-0a45-11e7-913c-ea69e90f4451.png)

**Comment by siddharthashw** [comment]
@rushi216 please provide feedback

**Comment by rushi216** [comment]
LGTM

**Comment by juliepromact** [comment]
It's better to name OAuthCredential table as AppCredential as it would be holding Slack app credentials too
