### ISSUE TITLE
Seprate(Task Mail Bot, Scrum Bot , Leave Command and Redmine command) Functionality

### ISSUE THREAD

**Issue by siddharthashw** [Promact/slack-erp-custom-integration-mvc#282]
Seprate(Task Mail Bot, Scrum Bot , Leave Command and Redmine command) Functionality as per wire frame in - #278

**Comment by siddharthashw** [comment]
Start Date : 16/03/2017
Estimated time : 14 hours
End Date : 20/03/2017

**Comment by siddharthashw** [comment]
Done my part.... Need to merge the part with @juliepromact and test for once.

On hold till get latest from @juliepromact sides

**Comment by siddharthashw** [comment]
@ankit213 and @chintans , should I re-start working on it. As it's almost done.

**Comment by ankit213** [comment]
Yes

**Comment by siddharthashw** [comment]
Start Date : 04/04/2017
Estimated time : 6 hours
End Date : 04/04/2017

**Comment by ankit213** [comment]
@siddharthashw :  This task is almost done right, so why you need 6 hours for this task?

**Comment by siddharthashw** [comment]
There are 4 module - task mail, scrum, leave command and redmine command.
And the separation part.

So I need to test them all for once.
