### ISSUE TITLE
After User Login Side Menu Not Working  

### ISSUE THREAD

**Issue by ankit213** [Promact/slack-erp-custom-integration-mvc#287]
[X] bug report => search github for a similar issue or PR before submitting             
[ ] feature request => 

**Step/s to reproduce issue**
Login with user then click on side menu option, but it' didn't work

**Screen shot**

**Comment by Asrapromact** [comment]
Start Date: 17-03-2017
End Date: 17-03-2017
Estimation time : 0.20 hour
