### ISSUE TITLE
"Object Reference not set to an instance of object" message for records that donot exist or incorrect usernames

### ISSUE THREAD

**Issue by karandesai28** [Promact/slack-erp-custom-integration-mvc#298]
**I'm submitting a ...**  (check one with "x")

[x ] bug report         
[ ] feature request => 

**Step/s to reproduce issue**
1. Integrate your slack app
2. Type command /leaves list ksdfsdf
3. Reply message is: "Object reference not set to an instance of an object". This is either because username is wrong or there is no record for leaves for that particular user. I believe, there should be a user understandable message.
Note: Same message comes on command: /leaves status fsdfsdf. When correct username is entered, it is working fine (/leaves status siddhartha and /leaves list siddhartha is working)

**Screen shot**
![1234](https://cloud.githubusercontent.com/assets/20238013/24090275/acdf1860-0d64-11e7-8eab-67a10d740e9f.PNG)

**Comment by siddharthashw** [comment]
Start Date : 20/03/2017
Estimated time : 1 hours
End Date : 20/03/2017

**Comment by siddharthashw** [comment]
Issue fixes - @karandesai28 ... Please check
