### ISSUE TITLE
Update static url so It can be changeable at run time

### ISSUE THREAD

**Issue by ankit213** [Promact/slack-erp-custom-integration-mvc#305]
UrlRtmStart - "https://slack.com/api/rtm.start"
OAuthAcessUrl - "https://slack.com/api/oauth.access"
SlackUserListUrl - "https://slack.com/api/users.list"
SlackChannelListUrl - "https://slack.com/api/channels.list"
SlackGroupListUrl - "https://slack.com/api/groups.list"
SlackChatUpdateUrl - "https://slack.com/api/chat.update"
LeaveManagementAuthorizationUrl - "https://slack.com/oauth/authorize"
ChatPostUrl - "https://slack.com/api/chat.postMessage"
OAuthAuthorizationScopeAndClientId - "?scope=incoming-webhook,commands,bot,users:read,groups:read,channels:read,chat:write:bot,chat:write:user&client_id="

Right now this all url are static in our ERP Project, but in future when there is the change in url it will not possible to edit this string.

**Comment by chintans** [comment]
What is the proposed solution?

**Comment by ankit213** [comment]
@chintans:  we will use appSettings in web config file or add appsetting json file and store the value in database 
so you give suggestion which one is better?

**Comment by chintans** [comment]
No need to store in DB. Let's assume we go with appsettings in web.config file. What keys will you add?

**Comment by ankit213** [comment]
@chintans 
**Key=UrlRtmStart** 
Value="https://slack.com/api/rtm.start"

**Key=OAuthAcessUrl**
Value="https://slack.com/api/oauth.access"

**Key=SlackUserListUrl**
Value="https://slack.com/api/users.list"

**Key=SlackChannelListUrl**
Value="https://slack.com/api/channels.list"

**Key=SlackGroupListUrl** 
Value="https://slack.com/api/groups.list"

**Key=SlackChatUpdateUrl**
Value="https://slack.com/api/chat.update"

**Key=LeaveManagementAuthorizationUrl**
Value="https://slack.com/oauth/authorize"

**Key=ChatPostUrl**
Value="https://slack.com/api/chat.postMessage"

**Key=OAuthAuthorizationScopeAndClientId**
Value = "?scope=incoming-webhook,commands,bot,users:read,groups:read,channels:read,chat:write:bot,chat:write:user&client_id="

is it ok?

**Comment by chintans** [comment]
No that is not OK. Please improve it and come up with better solution

**Comment by ankit213** [comment]
@chintans 
can we use multiple values for single config key like below link?
http://stackoverflow.com/questions/2819964/multiple-values-for-a-single-config-key

**or**

can we use external config file like below link ?
http://stackoverflow.com/questions/27691636/write-appsettings-in-external-file and give key value 

we use baseUrl = "https://slack.com/api/" as static because I think it is not going to change and remaining url is  

**Key=UrlRtmStart** 
Value="rtm.start"

**Key=OAuthAcessUrl**
Value="oauth.access"

**Key=SlackUserListUrl**
Value="users.list"

**Key=SlackChannelListUrl**
Value="channels.list"

**Key=SlackGroupListUrl** 
Value=groups.list"

**Key=SlackChatUpdateUrl**
Value="chat.update"

**Key=LeaveManagementAuthorizationUrl**
Value="https://slack.com/oauth/authorize"

**Key=ChatPostUrl**
Value="chat.postMessage"

**Key=OAuthAuthorizationScopeAndClientId**
Value = "?scope=incoming-webhook,commands,bot,users:read,groups:read,channels:read,chat:write:bot,chat:write:user&client_id="

**Comment by chintans** [comment]
No, both options are not OK. You need to understand one critical thing about 3rd party API. They usually don't change end points because millions of apps maybe using them. They may create versioning for that. In that case all current apps will be backward compatible. there is really no need for an appsettings but a restructure of url of each end point.
