### ISSUE TITLE
Bot does not respond even if it is active

### ISSUE THREAD

**Issue by juliepromact** [Promact/slack-erp-custom-integration-mvc#312]
**I'm submitting a ...**  

- [X] bug report => Bot does not respond even if it is active.
- [ ] feature request => 

**Step/s to reproduce issue**

1. Add a bot to any private channel.
2. Write commands which bot recognizes, it will respond.
3. Remove bot from the private channel and it stops responding even if it is added back to the private channel.

**Comment by juliepromact** [comment]
Start Date - 22/03/2017
Estimated time - 4 hours
End Date - 22/03/2017

**Comment by chintans** [comment]
Have you tried updating original SlackAPI ? From the actual repository?

**Comment by juliepromact** [comment]
No. I didn't try that

**Comment by juliepromact** [comment]
Their repository has the same issue
