### ISSUE TITLE
purpose of Post to while Add to Slack

### ISSUE THREAD

**Issue by chintans** [Promact/slack-erp-custom-integration-mvc#319]
**I'm submitting a ...**  (check one with "x")

- [ ] bug report => search github for a similar issue or PR before submitting             
- [x] feature request => 

**Step/s to reproduce issue**
After login with Promact while Adding Slack. There is a field called Post To. What is the requirement of that while adding Slack? 

**Screen shot**

**Comment by ankit213** [comment]
@chintans: It is for slash command. i.e. Bot that is used in slash command has to reply the user applying leave, where it will post that reply can be customized by the user at the authorize stage(post to)

**Comment by chintans** [comment]
How will user know this usage?

**Comment by chintans** [comment]
Is there possibility to change that later on? If yes, How?

**Comment by ankit213** [comment]
>How will user know this usage?

We will display message on add to slack page like "choose the channel on which you want bot (the bot which is used to as slash command) to reply to"

**Comment by siddharthashw** [comment]
>Is there possibility to change that later on? If yes, How?

If there will be any possibility then it will be from slack side. We are not able to change it. As we have used incoming web-hook, so for that, message will be displayed as per user choose the channel.

**Comment by chintans** [comment]
> We will display message on add to slack page like "choose the channel on which you want bot (the bot which is used to as slash command) to reply to"

Please provide a mockup for the functionality you are suggesting. make sure it is user friendly and easy to understand.

**Comment by chintans** [comment]
> If there will be any possibility then it will be from slack side. We are not able to change it. As we have used incoming web-hook, so for that, message will be displayed as per user choose the channel.

There needs to be a way to change this. even if it is from Slack side, There needs to be a documentation for it in application.

**Comment by siddharthashw** [comment]
>Please provide a mockup for the functionality you are suggesting. make sure it is user friendly and easy to understand.

![user-view for leave app](https://cloud.githubusercontent.com/assets/16556606/24659020/212a7c0e-1969-11e7-9da8-02be2c7a724d.png)

**Comment by siddharthashw** [comment]
>Please provide a mockup for the functionality you are suggesting. make sure it is user friendly and easy to understand.

![user-view for leave app](https://cloud.githubusercontent.com/assets/16556606/24659163/86ccb0b8-1969-11e7-95e3-6696fcae4adc.png)

This will only display to user, when leave app is added or active for application

**Comment by siddharthashw** [comment]
>There needs to be a way to change this. even if it is from Slack side.

We can use a custom incoming-webhook and leave related any message or any activity will be post in single channel.

>There needs to be a documentation for it in application.

After PR - #321 , this won't be required, because user will get proper message as above mockup
