### ISSUE TITLE
Documentation for Leave command

### ISSUE THREAD

**Issue by chintans** [Promact/slack-erp-custom-integration-mvc#324]
**I'm submitting a ...**  (check one with "x")

[ ] bug report => search github for a similar issue or PR before submitting             
- [x] feature request => 

**Step/s to reproduce issue**
There is no documentation on how to install and use leave command

**Screen shot**

**Comment by siddharthashw** [comment]
Start Date : 12/04/2017
Estimated time : 2 hours
End Date : 12/04/2017
