### ISSUE TITLE
Double Quotes are different for MAC and Windows users

### ISSUE THREAD

**Issue by juliepromact** [Promact/slack-erp-custom-integration-mvc#329]
**I'm submitting a ...**

- [x] bug report => search github for a similar issue or PR before submitting.                          
[ ] feature request => 

**Step/s to reproduce issue**

Send any quoted statement from Mac via Slack. It can be observed that the double quotes are curly unlike double quotes in Windows. This creates misinterpretation of slack commands.

**Comment by siddharthashw** [comment]
>Send any quoted statement from Mac via Slack. It can be observed that the double quotes are curly unlike double quotes in Windows. This creates misinterpretation of slack commands.

Suggestion is we can replace left and right double quotes to normal window double quotes. Then it will resolve the above issue. We can try this

**Comment by siddharthashw** [comment]
Start Date : 19/04/2017
Estimated time : 2 hours
End Date : 19/04/2017

Analysis Time includes in above estimation and optimal solution searching

**Comment by siddharthashw** [comment]
This has been resolved but yet not reflected on Production.
