### ISSUE TITLE
task mail bot enhancements

### ISSUE THREAD

**Issue by chintans** [Promact/slack-erp-custom-integration-mvc#339]
The task mail bot needs few improvements

1. Bot takes too much time in asking question. It should be extremely fast.
2. There is no easier way to know on how to write more tasks in a single task mail. Please improve user experience.

**Comment by siddharthashw** [comment]
>1. Bot takes too much time in asking question. It should be extremely fast.

For this I have one suggestion that we can remove OAuth call for getting user details every-time, will check for first time of that day is user is active or not. If Active, we can use our database to get authorize user details and conduct task mail else we will provide user with In-Active or Unauthorized message. 

>2. There is no easier way to know on how to write more tasks in a single task mail. Please improve user experience.

We can add one message at the end of task mail process for adding more tasks in a single task mail

@chintans Please provide your feedback.

**Comment by siddharthashw** [comment]
>There is no easier way to know on how to write more tasks in a single task mail. Please improve user experience.

This has been done in commit id - [1c4f9b2](https://github.com/Promact/slack-productivity-bots/commit/1c4f9b203d8d973f8f89b5621f20cee968b26229)

**Comment by siddharthashw** [comment]
>Bot takes too much time in asking question. It should be extremely fast.

This has been done in commit id - [228de3f](https://github.com/Promact/slack-productivity-bots/commit/228de3f4b8ca8644ab069755f528da2c080aaca2)

**Comment by ankit213** [comment]
@siddharthashw : Please update task mail bot flow , We need to add one more question after complete one task is "Do you want to add another task?" If answer is "Yes" then continue with task mail. if "No" then asked "Your task mail is ready. Do you want to send it?
To add more task in your mail please write "No" and wait for completion of this process. Then to add task please start, write *task mail*"

**Comment by siddharthashw** [comment]
Start Date : 11/05/2017
Estimated time : 16 hours
End Date : 15/05/2017

For server side code - 8 hours
For test cases updation and adding new - 6 hours
For testing - 2 hours
