### ISSUE TITLE
Oauth Call's Not working properly.

### ISSUE THREAD

**Issue by ankit213** [Promact/slack-erp-custom-integration-mvc#342]
**I'm submitting a ...**  (check one with "x")

-[x] bug report => search github for a similar issue or PR before submitting             
[ ] feature request => 

**Step/s to reproduce issue**
When I login with Promact at that time 500 error is occur. and also scrum bot not working

**Comment by siddharthashw** [comment]
Start Date : 09/05/2017
Estimated time : 5 hours
End Date : 09/05/2017
