### ISSUE TITLE
Remove unnecessary handling of events 

### ISSUE THREAD

**Issue by juliepromact** [Promact/slack-erp-custom-integration-mvc#358]
**I'm submitting a ...**  

- [x] bug report => search github for a similar issue or PR before submitting             
- [ ] feature request => 

**Step/s to reproduce issue**

**Screen shot**

**Comment by juliepromact** [comment]
Start Date - 01/06/2017
End Date - 01/06/2017
Estimated Time - 3.5 hours

**Comment by juliepromact** [comment]
@siddharthashw please do necessary changes in Task mail and Leave modules

**Comment by siddharthashw** [comment]
@juliepromact , will look into the matter. 
And do the necessary changes. Please don't comment any functionality for now. Do the changes and check-in even if gets error. I will do the required changes in same branch.

**Comment by juliepromact** [comment]
ok

**Comment by siddharthashw** [comment]
Start Date - 01/06/2017
End Date - 01/06/2017
Estimated Time - 2.5 hours
