### ISSUE TITLE
Login with Promact not working

### ISSUE THREAD

**Issue by chintans** [Promact/slack-erp-custom-integration-mvc#44]
After setting up all environment variables I tried to open LogIn with Promact. It showed 400 bad request error.

**Comment by siddharthashw** [comment]
It's normally working in my system and as well in Gourav's system. I think you must save the environment variable properly. I just check it out and verified

```
PromactOAuthClientId=BH49TZ6AP0VNMMV
PromactOAuthClientSecret=OSfkhxwiRJajodTBKklrqFYM0J2JD1
```
