### ISSUE TITLE
Sick Leave Flow

### ISSUE THREAD

**Issue by siddharthashw** [Promact/slack-erp-custom-integration-mvc#45]
What will be action after admin applies sick leave for an employee? Will all team leader and management get any slack message as casual leave and email regarding sick leave has been applied for the employee?
And the same question arise for sick leave update?

**Comment by iroshni** [comment]
- Sick leave can be applied by admin or employee by own.
- Admin can apply sick leave on behalf of an employee.
- Leave applied by admin can be more than one day but an employee can apply for max 1 day.
- All related people (team leaders and management. in case if leave is applied by admin, then employee will also get on behalf of whom admin has applied leave. ) will get notification mail/slack on sick leave application
- Only admin can update sick leave. and update also related people will get notification

kindly analyse the require on the above points and let me know in case any improvements required.

**Comment by siddharthashw** [comment]
Done the functionality as per your requirement
