### ISSUE TITLE
Create a common way to access all environment variables

### ISSUE THREAD

**Issue by chintans** [Promact/slack-erp-custom-integration-mvc#53]
Create a common way to access all environment variables quickly. Right now a common way of using it is to Environment.GetEnvironmentVariable("","Scope). Whenever this variable is re-used, there will be code repetition. Instead, create something that will unify it.

**Comment by juliepromact** [comment]
We may fetch all the environment variables and store it as Application State values in Application_Start method of Global.asax. This way there wouldn't be code repetition.
