### ISSUE TITLE
Create a success page after Slack authorization to add Slack to team

### ISSUE THREAD

**Issue by chintans** [Promact/slack-erp-custom-integration-mvc#64]
right now When we hit Add to Slack. It redirects a user to Slack for authentication and returns on a blank page. There is no way to know whether it was successful or failed. Please add a page which indicates the outcome. i.e, If It comes back successfully. It should show 

> Promact Slack app has been successfully 

if it comes back with a failure 

> Promact Slack app was not added successfully. There is something wrong Internally.

or there is a server side exception.

> Promact Slack app was not added successfully. {{REPLACE_THIS_WITH_ACTUAL_ERROR_RETURNED_FROM_SLACK}} 

And below this description add a button to continue which brings use back to Home page.

**Comment by juliepromact** [comment]
Estimated Time - 5 hour
Estimated Completion Date - 18/10/2016
