### ISSUE TITLE
In "Task Report" add loader.

### ISSUE THREAD

**Issue by ghost** [Promact/slack-erp-custom-integration-mvc#68]
Steps to be followed:

1) Open a link (https://promactslack.azurewebsites.net)
2) Then click on Login with Promact.
3) Then you may see "Task Report" when you click on it and you may see a text "Nothing is Loading Now" instead of text we may have a loader when we click on Task Report a loader must be installed the all the reports must be generated.

Please see the screenshot.
![2016-10-18_10-33-56](https://cloud.githubusercontent.com/assets/20476866/19465122/30b01d60-951f-11e6-9989-f2ab6bc3dc81.png)

**Comment by iamronakshah** [comment]
Estimated Time - 2 Hours
Estimated Completion Date - 18/10/2016
