### ISSUE TITLE
Loader is not implemented when we click on Login with promact.

### ISSUE THREAD

**Issue by ghost** [Promact/slack-erp-custom-integration-mvc#69]
Steps to be followed:

1) Open a link (https://promactslack.azurewebsites.net)
2) Then click on Login with promact.
3) When you click on it and you may see LOADING.. instead of that, we may use a loader.

Please see the screenshot.
![2016-10-18_11-01-27](https://cloud.githubusercontent.com/assets/20476866/19465500/600276e6-9522-11e6-964d-e3ffe8e6b99f.png)

**Comment by iamronakshah** [comment]
I have added loader in index.cshtml page. now onwards you can see the loader in the main page.
