### ISSUE TITLE
Designing is not proper in https://promactslack.azurewebsites.net

### ISSUE THREAD

**Issue by ghost** [Promact/slack-erp-custom-integration-mvc#71]
In this link https://promactslack.azurewebsites.net all the pages do not have proper designing.
List of pages:
1) Login Page.
2) Home Page.
3) Task Report.
4) Leave Report.

When we click on Task Mail Report the designing of the pages are not proper. Please fix the designing issue.

Please fix the designing issues.

Please see the screenshot:

![2016-10-26_11-46-57](https://cloud.githubusercontent.com/assets/20476866/19715374/5a849dce-9b72-11e6-9fc3-f88603bf48e2.png)

![2016-10-26_11-50-29](https://cloud.githubusercontent.com/assets/20476866/19715399/85ac2904-9b72-11e6-8e8a-ae1e1aa522a3.png)

![2016-10-26_11-53-20](https://cloud.githubusercontent.com/assets/20476866/19715474/0a6da15e-9b73-11e6-8835-7ae6cebdbad8.png)

**Comment by Asrapromact** [comment]
@hardikbhatt Designing for this project hasn't been yet started .

**Comment by ghost** [comment]
@Asrapromact to keep a track of pending issue i have added an issue.
