### ISSUE TITLE
Error is been occurred when we refresh the pages. 

### ISSUE THREAD

**Issue by ghost** [Promact/slack-erp-custom-integration-mvc#72]
Steps to be followed:

1) Open a link (https://promactslack.azurewebsites.net)
2) Click on Login with promact.
3) Then Click on Leave Report and Task Report, You may get the error.
The following links for which we are getting the error.
https://promactslack.azurewebsites.net/leave
https://promactslack.azurewebsites.net/task

Please see the screenshot.
![2016-10-18_10-56-47](https://cloud.githubusercontent.com/assets/20476866/19467636/da7ab548-952f-11e6-9a12-20301cc81192.png)

**Comment by iamronakshah** [comment]
Estimated Time - 2 Hours 
Estimated Completion Date - 19/10/2016
