### ISSUE TITLE
Logout functionality is not implemented. 

### ISSUE THREAD

**Issue by ghost** [Promact/slack-erp-custom-integration-mvc#80]
Logout functionality is not been implemented on Promact ERP, If user logins to see his reports then he may also be allowed to log out from the Promact ERP.

**Comment by gouravagrwal** [comment]
Started Date :18-11-2016
Estimated Time: 6 Hours
End Date :18-11-2016

**Comment by juliepromact** [comment]
Completed but not on dev branch.
