### ISSUE TITLE
implement identity authentication 

### ISSUE THREAD

**Issue by chintans** [Promact/slack-erp-custom-integration-mvc#83]
right now there is no authentication in the entire application. We need to implement proper identity authentication supporting oauth.

**Comment by iamronakshah** [comment]
Started Date :25-10-2016
Estimated Time: 3 Hours 30 min
End Date :25-10-2016

**Comment by iamronakshah** [comment]
I have updated home , task mail and leave report controllers in Promact.ERP Project. I have also decorated some methods by CustomAttribute in promact.oauth.
but not yet uploaded on dev.
