### ISSUE TITLE
remove all string from code

### ISSUE THREAD

**Issue by chintans** [Promact/slack-erp-custom-integration-mvc#86]
Currently, all strings are inside the code in a string constant. If I want to change any string, I would need to redeploy the application. Suggest a better way to manage text outside code and implement it.

**Comment by chintans** [comment]
What is the status on this?

**Comment by ankit213** [comment]
ronak has sent mail to you about this issue but your reply is pending.

**Comment by siddharthashw** [comment]
1) Created one json file which of string literal. (StringLiteral.json)
2) Created one class file which will content same property as json file.(AppStringLiteral.cs)
3) Created one singleton class which has Deserialize json file and assign the json file value in AppStringLiteral. (SingletonStringLiteral.cs)
4) Used file watcher in Global.asax for watching json file.
if any changes happen in json file  then reassign the value. so we get the latest value of string literal.

this is my suggestion, please review and provide feedback - @ankit213 and @chintans

**Comment by chintans** [comment]
@ankit213 Please review this and provide your feedback

**Comment by ankit213** [comment]
Yes this is fine for me, you can also use this for watcher [watcher class](https://msdn.microsoft.com/en-us/library/system.io.filesystemwatcher(v=vs.110).aspx)

**Comment by siddharthashw** [comment]
>you used also this for watcher [watcher class](https://msdn.microsoft.com/en-us/library/system.io.filesystemwatcher(v=vs.110).aspx)

Will look into the matter and try to use that class. Still analysis required

**Comment by siddharthashw** [comment]
Start Date : 05/04/2017
Estimated time : 7 hours 30 minutes
End Date : 05/04/2017

It take me, 7 hours and 30 minutes to implement and do proper testing.

I have implemented the issue, please once check branch - [`Issue-#86`](https://github.com/Promact/slack-productivity-bots/tree/Issue-%2386) and provide me feedback then will request for PR
