### ISSUE TITLE
scrum bot does not conclude scrum meeting

### ISSUE THREAD

**Issue by chintans** [Promact/slack-erp-custom-integration-mvc#87]
Scrum bot continued scrum meeting even after it said it concluded the meeting. It should lock the meeting.

**Comment by juliepromact** [comment]
In order for the scrum bot to deduce that a scrum has been concluded it checks whether all users' answers have been recorded.  No flag has been set to mark that a scrum of a team has been concluded. So the reason for such behaviour might be that before the members of this project (in OAuth) were A, B and C. Now it  has been edited to A,B and Z. So scrum bot saw that Z's answers are not recorded so it expects Z to answer.
