### ISSUE TITLE
Nlog - Exception File Path

### ISSUE THREAD

**Issue by siddharthashw** [Promact/slack-erp-custom-integration-mvc#9]
I had used Nlog in my project but I m not able to detect where the file is gone to be saved

**Comment by chintans** [comment]
I am not able to understand the issue. You have not provided any information for anyone to help you. Please update the issue with detailed description and proper title.

**Comment by siddharthashw** [comment]
As per tutorials, When some exception is thrown, It will write exceptions in a text file.
But in my case, when some exception is thrown, I am not able to detect that file of exception in any of the folder.

I had install Nlog.config from nuget and used        

``` csharp
var  _logger = LogManager.GetCurrentClassLogger();

//In Controller
 _logger.Error(ex, "StringErrorMessage");
```

_and this is my Nlog.config file_

``` XML
<?xml version="1.0" encoding="utf-8" ?>
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="http://www.nlog-project.org/schemas/NLog.xsd NLog.xsd"
      autoReload="true"
      throwExceptions="false"
      internalLogLevel="Off" internalLogFile="c:\temp\nlog-internal.log">
  <variable name="myvar" value="myvalue"/>
  <variable name="logDirectory" value="${basedir}/logs/${shortdate}"/>
  <targets>
    <target name="logfile" xsi:type="File" fileName="${logDirectory}/file.txt" />
  </targets>
  <rules>
    <!-- add your logging rules here -->
    <logger name="*" minlevel="Error" writeTo="logfile" />
  </rules>
</nlog>
```

**Comment by siddharthashw** [comment]
I have resolved the issue of file not generating. And its now ready to use
