### ISSUE TITLE
improve scrum bot implementation

### ISSUE THREAD

**Issue by chintans** [Promact/slack-erp-custom-integration-mvc#90]
think scrum bot needs a change in implementation.
1. Job of the scrum bot is to conduct scrum meeting only
2. Instead of using something like "scrum time" we can use "@scrumstaging start". It is much better way to start.
3. Once a meeting is completed. It should not allow another scrum meeting during that day.
4. If somebody tries 2nd scrum meeting. It should reply something like "meeting is done for today. Try again tomorrow."
5. As an enhancement, we can look to add force start even if a meeting is conducted in a day already.

**Comment by juliepromact** [comment]
1. The only job that scrum bot does is to conduct scrum meeting – but as we have to save the data of the scrum and link it with Oauth, there needs to be some initial setup such as Logging in with Promact-OAuth. These are done just once. So the messages that come in between now wouldn't be an issue in the long run.
2. The command "@scrumstaging start" is received as "U97760900 start" i.e. "SlackUserId start". There are issues with this command. 
First being, we do not store bot users details in our database so @scrumstaging cannot be identified.
Second being, what if the bot changes and it is @scrumbot.
3. Scrum time is conducted just once in a day. At present it is not allowed to start a scrum meeting again on the same day for the same project/channel. The messages can be changed after scrum conclusion will be changed
4. The reply would be changed and could vary depending upon whether members were marked to answer later.
5. A modified enhancement of forcibly starting a scrum meeting was suggested earlier(not in git hub). What I suggested was to discard the scrum meeting of the day and start scrum meeting all over again. 
Do you intend something similar ? Discard the previous scrum of the day or keep both ?

**Comment by juliepromact** [comment]
> 1) Job of the scrum bot is to conduct scrum meeting only

The only job that scrum bot does is to conduct scrum meeting – but as we have to save the data of the scrum and link it with Oauth, there needs to be some initial setup such as Logging in with Promact-OAuth. These are done just once. So the messages that come in between now wouldn't be an issue in the long run.

> 2) Instead of using something like "scrum time" we can use "@scrumstaging start". It is much better way to start.

 The command "@scrumstaging start" is received as "U97760900 start" i.e. "SlackUserId start". There are issues with this command.  
    First being, we do not store bot users details in our database so @scrumstaging cannot be identified. 
    Second being,  what if the bot changes and it is @scrumbot ?

> 3) Once a meeting is completed. It should not allow another scrum meeting during that day.

 Scrum time is conducted just once in a day. At present it is not allowed to start a scrum meeting again on the same day for the same project/channel. The messages can be changed after scrum conclusion will be changed.

> 4) If somebody tries 2nd scrum meeting. It should reply something like "meeting is done for today. Try again tomorrow."

The reply would be changed and could vary depending upon whether members were marked to answer later.

> 5) As an enhancement, we can look to add force start even if a meeting is conducted in a day already.

A modified enhancement of forcibly starting a scrum meeting was suggested earlier(not in git hub). What I suggested was to discard the scrum meeting of the day and start scrum meeting all over again. @chintans , do you intend something similar ? Discard the previous scrum of the day or keep both ?

**Comment by juliepromact** [comment]
Start Date : 26-10-2016 
Estimated Time : 24 Hours
End Date : 3-11-2016

**Comment by chintans** [comment]
> The only job that scrum bot does is to conduct scrum meeting – but as we have to save the data of the scrum and link it with OAuth, there needs to be some initial setup such as Logging in with Promact-OAuth. These are done just once. So the messages that come in between now wouldn't be an issue in the long run.

For scrum bot, It needs to conduct scrum meeting for users who are there in Project in OAuth server. Any other member needs to be ignored. Issues are never long term or short term. They are just issues and issues needs proper handling.

> The command "@scrumstaging start" is received as "U97760900 start" i.e. "SlackUserId start". There are issues with this command.
> First being, we do not store bot users details in our database so @scrumstaging cannot be identified. 
> Second being, what if the bot changes and it is @scrumbot ?

Create a separate bot table and store all bots for the mapping purpose.

> Scrum time is conducted just once in a day. At present it is not allowed to start a scrum meeting again on the same day for the same project/channel. The messages can be changed after scrum conclusion will be changed.

Agreed

> The reply would be changed and could vary depending upon whether members were marked to answer later.

Don't create later functionality. It just creates confusion. there could be a better way to a person to talk to scrum bot and inform it about missed scrum meeting and report status separately. for now, reply later functionality should be removed.

> A modified enhancement of forcibly starting a scrum meeting was suggested earlier(not in git hub). What I suggested was to discard the scrum meeting of the day and start scrum meeting all over again. @chintans , do you intend something similar ? Discard the previous scrum of the day or keep both ?

I am thinking of keeping both. But as I said it's future enhancement. We will not implement this in 1st version.
